# -*- coding: utf-8 -*-
"""Advanced Credit Decisioning System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w7DDxJXPxCbhKquaqtVYXTTUdUfzf_1G
"""

!pip -q install pandas numpy scikit-learn xgboost lightgbm shap optuna seaborn matplotlib missingno fairlearn ydata-profiling category-encoders kagglehub

import os, glob, json, warnings, gc, math, itertools
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
pd.set_option('display.max_columns', 300)

import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

from scipy import stats
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.preprocessing import RobustScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.metrics import (roc_auc_score, average_precision_score, f1_score,
                             brier_score_loss, precision_recall_curve, roc_curve)
from sklearn.calibration import CalibratedClassifierCV
from sklearn.linear_model import LogisticRegression

import shap
import optuna
from fairlearn.metrics import (MetricFrame, selection_rate, true_positive_rate)
import joblib

import lightgbm as lgb

np.random.seed(42)

import kagglehub

# Download latest version
path = kagglehub.dataset_download("adarshsng/lending-club-loan-data-csv")

print("Path to dataset files:", path)

import os
import pandas as pd

# List files in the path provided by kagglehub
files = os.listdir(path)
print(f'Files in {path}:')
for f in files:
    print(f'- {f}')

import pandas as pd

# Load the dataset
csv_path = os.path.join(path, 'loan.csv')
df = pd.read_csv(csv_path, low_memory=False)

# Display first few rows
print('First 5 rows of the dataset:')
display(df.head())

# Check unique values in loan_status
if 'loan_status' in df.columns:
    print('\nUnique values in loan_status:')
    print(df['loan_status'].unique())
else:
    print('\nColumn loan_status not found.')

# Data summary
print('\nDataFrame Info:')
df.info()

missing_percentage = df.isnull().sum() / len(df) * 100
high_missing_cols = missing_percentage[missing_percentage >= 0.5].index.tolist()

print(f"Columns with 1% or more missing values: {len(high_missing_cols)}")
print(high_missing_cols)

df.drop(columns=high_missing_cols, inplace=True)

print(f"Total number of columns remaining in df: {df.shape[1]}")

initial_rows = df.shape[0]

# Calculate the percentage of missing values for each row
missing_percentage_rows = df.isnull().sum(axis=1) / df.shape[1] * 100

# Identify rows where missing_percentage_rows is 1% or greater
high_missing_rows_indices = missing_percentage_rows[missing_percentage_rows >= 1].index

# Drop these identified rows from the df DataFrame
df.drop(index=high_missing_rows_indices, inplace=True)

# Calculate the number of dropped rows
dropped_rows_count = initial_rows - df.shape[0]

print(f"Number of rows dropped: {dropped_rows_count}")
print(f"Total number of rows remaining in df: {df.shape[0]}")

data_leakage_cols = [
    'funded_amnt', 'issue_d', 'out_prncp', 'out_prncp_inv',
    'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
    'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
    'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d',
    'hardship_flag', 'hardship_type', 'hardship_reason', 'hardship_status',
    'deferral_term', 'hardship_amount', 'hardship_start_date', 'hardship_end_date',
    'payment_plan_start_date', 'hardship_length', 'hardship_dpd',
    'hardship_loan_status', 'orig_projected_additional_payments_by_equity',
    'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
    'debt_settlement_flag', 'debt_settlement_flag_date', 'settlement_status',
    'settlement_date', 'settlement_amount', 'settlement_percentage',
    'settlement_term'
]

initial_num_columns = df.shape[1]

# Filter data_leakage_cols to include only columns present in df
actual_leakage_cols_to_drop = [col for col in data_leakage_cols if col in df.columns]

# Drop the identified data leakage columns
df.drop(columns=actual_leakage_cols_to_drop, inplace=True)

dropped_columns_count = initial_num_columns - df.shape[1]

print(f"Number of columns dropped due to data leakage: {dropped_columns_count}")
print(f"Total number of columns remaining in df: {df.shape[1]}")

df['is_bad_loan'] = df['loan_status'].isin(['Charged Off', 'Default']) # Create the target variable

# Perform stratified sampling
_, df_sampled = train_test_split(
    df,
    test_size=200000,
    stratify=df['is_bad_loan'],
    random_state=42
)

print(f"Shape of df_sampled: {df_sampled.shape}")

print("\nDistribution of 'is_bad_loan' in original df:")
print(df['is_bad_loan'].value_counts())
print((df['is_bad_loan'].value_counts() / len(df) * 100).round(2))

print("\nDistribution of 'is_bad_loan' in df_sampled:")
print(df_sampled['is_bad_loan'].value_counts())
print((df_sampled['is_bad_loan'].value_counts() / len(df_sampled) * 100).round(2))

"""## Rebalance Target Variable in Sampled Data

### Subtask:
Adjust the class distribution within the `df_sampled` DataFrame to achieve approximately 65% 'False' (good loans) and 35% 'True' (bad loans) for the 'is_bad_loan' target variable. This will involve separating the majority and minority classes, randomly undersampling the majority class and randomly oversampling the minority class, and then combining them into a new DataFrame called `df_resampled`. Verify the new distribution.

"""

from sklearn.utils import resample

# Separate majority and minority classes
df_majority = df_sampled[df_sampled['is_bad_loan'] == False]
df_minority = df_sampled[df_sampled['is_bad_loan'] == True]

# Desired number of samples for each class
target_total_samples = 200000 # Keeping the total number of samples as 200,000
target_majority_count = int(target_total_samples * 0.65)
target_minority_count = int(target_total_samples * 0.35)

# Undersample majority class
df_majority_undersampled = resample(df_majority,
                                    replace=False,    # sample without replacement
                                    n_samples=target_majority_count, # to match desired count
                                    random_state=42)  # reproducible results

# Oversample minority class
df_minority_oversampled = resample(df_minority,
                                   replace=True,     # sample with replacement
                                   n_samples=target_minority_count,  # to match desired count
                                   random_state=42)   # reproducible results

# Combine resampled results
df_resampled = pd.concat([df_majority_undersampled, df_minority_oversampled])

print(f"Shape of df_resampled: {df_resampled.shape}")

print("\nDistribution of 'is_bad_loan' in df_resampled:")
print(df_resampled['is_bad_loan'].value_counts())
print((df_resampled['is_bad_loan'].value_counts() / len(df_resampled) * 100).round(2))

"""## Split Data into Train, Validation, and Test Sets

### Subtask:
Split the newly `df_resampled` DataFrame (200,000 rows) into three sets: 75% for training (`df_train`), 15% for validation (`df_val`), and 10% for testing (`df_test`). Ensure stratification by the 'is_bad_loan' target variable during the splits to maintain consistent class proportions across all subsets. The subsequent EDA will be performed on the training set.

"""

from sklearn.model_selection import train_test_split

# Step 1: Split df_resampled into training (75%) and temp (25%) sets
df_train, df_temp, _, _ = train_test_split(
    df_resampled,
    df_resampled['is_bad_loan'],
    test_size=0.25,
    stratify=df_resampled['is_bad_loan'],
    random_state=42
)

# Step 2: Split df_temp (25% of original) into validation (15%) and test (10%) sets
# Calculate the test_size for the second split:
# We want df_val to be 15% of original (0.15) and df_test to be 10% of original (0.10)
# df_temp is 25% of original (0.25)
# So, df_val will be 0.15 / 0.25 = 0.60 of df_temp
# And df_test will be 0.10 / 0.25 = 0.40 of df_temp

df_val, df_test, _, _ = train_test_split(
    df_temp,
    df_temp['is_bad_loan'],
    test_size=0.40, # 0.10 (desired test_size) / 0.25 (current df_temp size) = 0.40
    stratify=df_temp['is_bad_loan'],
    random_state=42
)

# Verify the shapes of the resulting DataFrames
print(f"Shape of df_train: {df_train.shape}")
print(f"Shape of df_val: {df_val.shape}")
print(f"Shape of df_test: {df_test.shape}")

# Display the distribution of 'is_bad_loan' in each DataFrame
print("\nDistribution of 'is_bad_loan' in df_train:")
print(df_train['is_bad_loan'].value_counts())
print((df_train['is_bad_loan'].value_counts() / len(df_train) * 100).round(2))

print("\nDistribution of 'is_bad_loan' in df_val:")
print(df_val['is_bad_loan'].value_counts())
print((df_val['is_bad_loan'].value_counts() / len(df_val) * 100).round(2))

print("\nDistribution of 'is_bad_loan' in df_test:")
print(df_test['is_bad_loan'].value_counts())
print((df_test['is_bad_loan'].value_counts() / len(df_test) * 100).round(2))

"""## Categorize Features in Training Set

### Subtask:
After splitting, categorize the features in the training set (`df_train`) into numerical, categorical, and date-time types. Display the count and names of features in each category for clarity, as these lists will be used for subsequent EDA steps.

"""

numerical_cols_train = df_train.select_dtypes(include=np.number).columns.tolist()
categorical_cols_train = df_train.select_dtypes(include='object').columns.tolist()
datetime_cols_train = df_train.select_dtypes(include=['datetime64']).columns.tolist()

print(f"Number of numerical features in df_train: {len(numerical_cols_train)}")
print(f"Numerical features: {numerical_cols_train}\n")

print(f"Number of categorical features in df_train: {len(categorical_cols_train)}")
print(f"Categorical features: {categorical_cols_train}\n")

print(f"Number of date-time features in df_train: {len(datetime_cols_train)}")
print(f"Date-time features: {datetime_cols_train}")

"""## Visualize Missing Value Distribution (Training Set)

### Subtask:
Generate a clearer visualization of missing data across the columns of the `df_train` (training set) using `missingno.bar()` or a similar bar chart. This will provide a quick and intuitive overview of data completeness in the subset used for EDA.

**Reasoning**:
The subtask requires visualizing the missing data distribution in `df_train` using `missingno.bar()`. This step will generate and display the requested bar chart.
"""

import missingno as msno

# Generate a bar chart of missing values for df_train
msno.bar(df_train, figsize=(20, 8), color="dodgerblue", fontsize=12)
plt.title('Missing Values Distribution in Training Set', fontsize=16)
plt.show()

"""## Univariate Analysis for Numerical Features (Training Set)

### Subtask:
Perform univariate analysis for each numerical feature in the `df_train`. This includes generating descriptive statistics, visualizing distributions with histograms, and identifying outliers with box plots. Pay attention to the scale and range of values.

### Univariate Analysis for Numerical Features

For each numerical feature in `df_train`, the following analysis will be performed:
1.  **Descriptive Statistics**: To get a summary of central tendency, dispersion, and shape of the distribution.
2.  **Histogram**: To visualize the distribution shape, identify modes, and assess skewness.
3.  **Box Plot**: To identify potential outliers and visualize the spread and median of the data.

**Reasoning**:
Now I will iterate through each numerical column in `df_train` to perform univariate analysis by printing descriptive statistics, generating a histogram, and creating a box plot, as specified in the subtask instructions.
"""

for col in numerical_cols_train:
    print(f"\n--- Analyzing Numerical Feature: {col} ---")

    # 1. Descriptive Statistics
    print("Descriptive Statistics:")
    display(df_train[col].describe())

    # 2. Histogram
    plt.figure(figsize=(10, 6))
    sns.histplot(df_train[col].dropna(), kde=True, color='skyblue')
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')
    plt.grid(axis='y', alpha=0.75)
    plt.show()

    # 3. Box Plot
    plt.figure(figsize=(10, 2))
    sns.boxplot(x=df_train[col].dropna(), color='lightcoral')
    plt.title(f'Box Plot of {col}')
    plt.xlabel(col)
    plt.grid(axis='x', alpha=0.75)
    plt.show()

"""## Bivariate Analysis for Numerical Features (Training Set)

### Subtask:
For each numerical feature in `df_train`, perform bivariate analysis against the 'is_bad_loan' target variable. This involves creating box plots to compare distributions for good vs. bad loans and conducting independent samples t-tests (or Mann–Whitney U test for non-normal data) to check for statistically significant differences in means between the two target groups.

### Bivariate Analysis for Numerical Features against 'is_bad_loan'

For each numerical feature in `df_train`, the following bivariate analysis will be performed:
1.  **Box Plot**: To visualize the distribution of the numerical feature for both 'good loans' (False) and 'bad loans' (True) and identify differences in their central tendency and spread.
2.  **Independent Samples t-test**: To statistically assess if there is a significant difference in the means of the numerical feature between the two target groups ('is_bad_loan' == False vs. 'is_bad_loan' == True). The t-test assumes normality and equal variances. If these assumptions are not met, the p-value should be interpreted with caution. Alternatively, a non-parametric test like the Mann–Whitney U test could be considered if data is heavily non-normal.

**Reasoning**:
Now, I will iterate through each numerical column in `numerical_cols_train` to perform bivariate analysis by generating a box plot against the 'is_bad_loan' target variable and conducting an independent samples t-test between the two target groups, printing the statistical results.
"""

from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns

for col in numerical_cols_train:
    print(f"\n--- Bivariate Analysis for {col} vs. is_bad_loan ---")

    # 1. Box Plot
    plt.figure(figsize=(10, 6))
    sns.boxplot(x='is_bad_loan', y=col, data=df_train)
    plt.title(f'Box Plot of {col} by Loan Status')
    plt.xlabel('Is Bad Loan')
    plt.ylabel(col)
    plt.grid(axis='y', alpha=0.75)
    plt.show()

    # 2. Independent Samples t-test
    # Drop NA values for the current column and is_bad_loan to ensure valid comparison
    temp_df = df_train[[col, 'is_bad_loan']].dropna()

    # Separate data into two groups
    group_false = temp_df[temp_df['is_bad_loan'] == False][col]
    group_true = temp_df[temp_df['is_bad_loan'] == True][col]

    if len(group_false) > 1 and len(group_true) > 1: # Ensure there's enough data for t-test
        t_statistic, p_value = stats.ttest_ind(group_false, group_true, equal_var=False) # Welch's t-test assuming unequal variances
        print(f"Independent Samples t-test for {col}:")
        print(f"  t-statistic: {t_statistic:.4f}")
        print(f"  p-value: {p_value:.4f}")

        if p_value < 0.05:
            print("  Interpretation: There is a statistically significant difference in the mean of this feature between good and bad loans (p < 0.05).")
        else:
            print("  Interpretation: No statistically significant difference in the mean of this feature between good and bad loans (p >= 0.05).")
    else:
        print(f"  Not enough data in both groups for {col} to perform t-test.")

"""## Univariate Analysis for Categorical Features (Training Set)

### Subtask:
Perform univariate analysis for each categorical feature in the `df_train`. This includes displaying value counts and visualizing distributions using count plots to understand the frequency of each category.

**Reasoning**:
Now, I will iterate through each categorical column in `df_train` to perform univariate analysis by displaying value counts and generating count plots, as specified in the subtask instructions.
"""

for col in categorical_cols_train:
    print(f"\n--- Analyzing Categorical Feature: {col} ---")

    # 1. Value Counts
    print("Value Counts:")
    display(df_train[col].value_counts())

    # 2. Count Plot
    plt.figure(figsize=(12, 6))
    sns.countplot(y=col, data=df_train, order=df_train[col].value_counts().index, palette='viridis')
    plt.title(f'Count Plot of {col}')
    plt.xlabel('Count')
    plt.ylabel(col)
    plt.grid(axis='x', alpha=0.75)
    plt.show()

"""## Bivariate Analysis for Categorical Features (Training Set)

### Subtask:
For each categorical feature in df_train, perform bivariate analysis against the 'is_bad_loan' target variable. This involves creating stacked bar charts to show the proportion of good/bad loans within each category. Additionally, conduct Chi-square tests of independence and calculate Cramér’s V to quantify the strength of association between categorical features and the target.

### Bivariate Analysis for Categorical Features against 'is_bad_loan'

For each categorical feature in `df_train`, the following bivariate analysis will be performed:
1.  **Stacked Bar Chart**: To visualize the proportion of 'good loans' (False) and 'bad loans' (True) within each category of the feature.
2.  **Chi-square Test of Independence**: To statistically assess if there is a significant association between the categorical feature and 'is_bad_loan'.
3.  **Cramér's V**: To quantify the strength of the association between the two categorical variables, providing a measure of effect size.

**Reasoning**:
Now, I will iterate through each categorical column in `df_train` to perform bivariate analysis by generating stacked bar charts, conducting Chi-square tests of independence, and calculating Cramér’s V, as specified in the subtask instructions.
"""

from scipy.stats import chi2_contingency
import numpy as np

def cramers_v(confusion_matrix):
    """ Calculate Cramér's V statistic for a contingency table. """
    chi2 = chi2_contingency(confusion_matrix)[0]
    n = confusion_matrix.sum().sum()
    r, k = confusion_matrix.shape
    # Handle cases where k or r might be 1 to avoid division by zero
    phi2 = chi2 / n
    if min(k - 1, r - 1) == 0:
        return 0.0 # Return 0 if one of the dimensions is 1 (no association possible)
    v = np.sqrt(phi2 / min(k - 1, r - 1))
    return v

for col in categorical_cols_train:
    if col == 'loan_status': # Skip 'loan_status' as it's the direct source for 'is_bad_loan'
        continue

    print(f"\n--- Bivariate Analysis for {col} vs. is_bad_loan ---")

    # 1. Contingency Table
    contingency_table = pd.crosstab(df_train[col], df_train['is_bad_loan'])
    print("Contingency Table:")
    display(contingency_table)

    # 2. Stacked Bar Chart
    plt.figure(figsize=(12, 7))
    # Normalize by index to get proportions within each category
    contingency_table_normalized = contingency_table.div(contingency_table.sum(axis=1), axis=0)
    contingency_table_normalized.plot(kind='bar', stacked=True, figsize=(12, 7), colormap='viridis')
    plt.title(f'Proportion of Bad Loans by {col}')
    plt.xlabel(col)
    plt.ylabel('Proportion')
    plt.xticks(rotation=45, ha='right')
    plt.legend(title='Is Bad Loan', labels=['Good Loan', 'Bad Loan'])
    plt.tight_layout()
    plt.show()

    # 3. Chi-square Test of Independence
    if not contingency_table.empty and (contingency_table.sum(axis=1) > 0).all():
        chi2, p_value, dof, expected = chi2_contingency(contingency_table)
        print(f"Chi-square Test for {col}:")
        print(f"  Chi-square statistic: {chi2:.4f}")
        print(f"  P-value: {p_value:.4f}")

        if p_value < 0.05:
            print("  Interpretation: There is a statistically significant association between this feature and loan status (p < 0.05).")
        else:
            print("  Interpretation: No statistically significant association between this feature and loan status (p >= 0.05).")
    else:
        print(f"  Not enough data or invalid contingency table for Chi-square test for {col}.")

    # 4. Cramér's V
    if not contingency_table.empty and (contingency_table.sum().sum() > 0):
        v_score = cramers_v(contingency_table)
        print(f"Cramér's V for {col}: {v_score:.4f}")
        if v_score < 0.1:
            print("  Interpretation: Very weak association.")
        elif v_score < 0.2:
            print("  Interpretation: Weak association.")
        elif v_score < 0.4:
            print("  Interpretation: Moderate association.")
        elif v_score < 0.6:
            print("  Interpretation: Strong association.")
        else:
            print("  Interpretation: Very strong association.")
    else:
        print(f"  Not enough data or invalid contingency table for Cramér's V for {col}.")

"""## Multicollinearity Check for Numerical Features (Training Set)

### Subtask:
Assess multicollinearity among numerical features in the `df_train`. Calculate the Variance Inflation Factor (VIF) for each numerical feature to identify features that are highly correlated with others. Address highly collinear features by either dropping one or combining them, if appropriate.

### Multicollinearity Check for Numerical Features (Training Set)

To assess multicollinearity among numerical features in `df_train`, we will calculate the Variance Inflation Factor (VIF) for each feature. This will help identify features that are highly correlated with others, which can impact model stability and interpretability.

**Steps:**
1.  **Prepare Data**: Create a DataFrame `X` with only numerical features from `df_train`, excluding the target variable and any constant columns. Handle missing values by dropping rows.
2.  **Add Constant**: Add an intercept term to `X` for correct VIF calculation.
3.  **Calculate VIF**: Compute VIF for each feature.
4.  **Analyze Results**: Print VIF values and identify highly correlated features (typically VIF > 5 or 10).

**Reasoning**:
Now, I will implement the multicollinearity check using VIF by importing necessary libraries, preparing the numerical data, adding a constant, calculating VIFs, and displaying them, as detailed in the instructions.
"""

import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

# Exclude the target variable from numerical_cols_train for VIF calculation
numerical_features_for_vif = [col for col in numerical_cols_train if col != 'is_bad_loan']

# Create a new DataFrame X containing only the numerical features
X = df_train[numerical_features_for_vif].copy()

# Drop rows with NaN values from X to avoid issues with VIF calculation
X.dropna(inplace=True)

# Add a constant to X for VIF calculation
X_const = sm.add_constant(X)

# Calculate VIF for each feature
vif_data = pd.DataFrame()
vif_data['feature'] = X_const.columns
vif_data['VIF_value'] = [variance_inflation_factor(X_const.values, i) for i in range(X_const.shape[1])]

# Drop the 'const' row as it's an artificial feature for calculation
vif_data = vif_data[vif_data['feature'] != 'const']

# Sort VIF values in descending order
vif_data = vif_data.sort_values(by='VIF_value', ascending=False).reset_index(drop=True)

print("Variance Inflation Factor (VIF) values for numerical features:")
display(vif_data)

# Identify features with high VIF
high_vif_features = vif_data[vif_data['VIF_value'] > 5]
if not high_vif_features.empty:
    print("\nFeatures with VIF > 5 (indicating high multicollinearity):")
    display(high_vif_features)
else:
    print("\nNo features with VIF > 5.")

"""**Reasoning**:
The VIF analysis identified several highly collinear numerical features. Before dropping them, I'll first check the unique values of `policy_code` to confirm if it's a constant feature, which would explain its high VIF and warrant its removal.


"""

print("Unique values for 'policy_code':")
print(df_train['policy_code'].unique())
print("\nValue counts for 'policy_code':")
print(df_train['policy_code'].value_counts())

"""**Reasoning**:
Since 'policy_code' is a constant feature as confirmed by its unique values, it offers no predictive power and contributes to multicollinearity. Therefore, it should be removed from the dataset. Additionally, 'funded_amnt_inv' is highly correlated with 'loan_amnt' and 'installment' is often derived from 'loan_amnt', 'int_rate', and 'term'. To address the high multicollinearity observed, I will drop these three features and then recalculate VIFs.


"""

cols_to_drop_vif = ['policy_code', 'funded_amnt_inv', 'installment']

# Drop these columns from all datasets
df_train.drop(columns=cols_to_drop_vif, inplace=True)
df_val.drop(columns=cols_to_drop_vif, inplace=True)
df_test.drop(columns=cols_to_drop_vif, inplace=True)

print(f"Dropped columns: {cols_to_drop_vif}")
print(f"New shape of df_train: {df_train.shape}")

# Update numerical_cols_train after dropping columns
numerical_cols_train = [col for col in numerical_cols_train if col not in cols_to_drop_vif]

# Re-calculate VIF for the remaining numerical features

# Exclude the target variable from numerical_cols_train for VIF calculation
numerical_features_for_vif = [col for col in numerical_cols_train if col != 'is_bad_loan']

# Create a new DataFrame X containing only the numerical features
X = df_train[numerical_features_for_vif].copy()

# Drop rows with NaN values from X to avoid issues with VIF calculation
X.dropna(inplace=True)

# Add a constant to X for VIF calculation
X_const = sm.add_constant(X)

# Calculate VIF for each feature
vif_data_recalculated = pd.DataFrame()
vif_data_recalculated['feature'] = X_const.columns
vif_data_recalculated['VIF_value'] = [variance_inflation_factor(X_const.values, i) for i in range(X_const.shape[1])]

# Drop the 'const' row as it's an artificial feature for calculation
vif_data_recalculated = vif_data_recalculated[vif_data_recalculated['feature'] != 'const']

# Sort VIF values in descending order
vif_data_recalculated = vif_data_recalculated.sort_values(by='VIF_value', ascending=False).reset_index(drop=True)

print("\nRecalculated Variance Inflation Factor (VIF) values for numerical features:")
display(vif_data_recalculated)

# Identify features with high VIF after dropping
high_vif_features_recalculated = vif_data_recalculated[vif_data_recalculated['VIF_value'] > 5]
if not high_vif_features_recalculated.empty:
    print("\nFeatures with VIF > 5 (indicating high multicollinearity) after dropping:")
    display(high_vif_features_recalculated)
else:
    print("\nNo features with VIF > 5 after dropping selected columns.")

"""**Reasoning**:
Since 'pub_rec' still has a VIF close to 10 and 'tax_liens' is above 5, indicating remaining multicollinearity, I will drop 'pub_rec' (the one with higher VIF) and then recalculate VIFs to ensure that multicollinearity is sufficiently addressed.


"""

cols_to_drop_vif_further = ['pub_rec']

# Drop these columns from all datasets
df_train.drop(columns=cols_to_drop_vif_further, inplace=True)
df_val.drop(columns=cols_to_drop_vif_further, inplace=True)
df_test.drop(columns=cols_to_drop_vif_further, inplace=True)

print(f"Dropped columns: {cols_to_drop_vif_further}")
print(f"New shape of df_train: {df_train.shape}")

# Update numerical_cols_train after dropping columns
numerical_cols_train = [col for col in numerical_cols_train if col not in cols_to_drop_vif_further]

# Re-calculate VIF for the remaining numerical features

# Exclude the target variable from numerical_cols_train for VIF calculation
numerical_features_for_vif = [col for col in numerical_cols_train if col != 'is_bad_loan']

# Create a new DataFrame X containing only the numerical features
X = df_train[numerical_features_for_vif].copy()

# Drop rows with NaN values from X to avoid issues with VIF calculation
X.dropna(inplace=True)

# Add a constant to X for VIF calculation
X_const = sm.add_constant(X)

# Calculate VIF for each feature
vif_data_final = pd.DataFrame()
vif_data_final['feature'] = X_const.columns
vif_data_final['VIF_value'] = [variance_inflation_factor(X_const.values, i) for i in range(X_const.shape[1])]

# Drop the 'const' row as it's an artificial feature for calculation
vif_data_final = vif_data_final[vif_data_final['feature'] != 'const']

# Sort VIF values in descending order
vif_data_final = vif_data_final.sort_values(by='VIF_value', ascending=False).reset_index(drop=True)

print("\nFinal Variance Inflation Factor (VIF) values for numerical features:")
display(vif_data_final)

# Identify features with high VIF after dropping
high_vif_features_final = vif_data_final[vif_data_final['VIF_value'] > 5]
if not high_vif_features_final.empty:
    print("\nFeatures with VIF > 5 (indicating high multicollinearity) after final dropping:")
    display(high_vif_features_final)
else:
    print("\nNo features with VIF > 5 after final dropping of selected columns.")

"""## Final Task

### Subtask:
Summarize the initial data cleaning and comprehensive EDA findings from the sampled and split dataset, highlighting key insights gained about feature distributions, relationships with the target variable, and data quality issues.

## Summary:

### Data Analysis Key Findings

*   The `is_bad_loan` target variable in the sampled dataset was successfully rebalanced to a distribution of 65% 'False' (good loans) and 35% 'True' (bad loans), resulting in a `df_resampled` DataFrame of 200,000 entries.
*   The rebalanced dataset (`df_resampled`) was stratified and split into training, validation, and test sets with the following proportions and sizes:
    *   `df_train`: 75% (150,000 entries)
    *   `df_val`: 15% (30,000 entries)
    *   `df_test`: 10% (20,000 entries)
    The 'is_bad_loan' distribution remained consistent (65% 'False', 35% 'True') across all three subsets.
*   Feature categorization in the training set (`df_train`) identified 20 numerical features, 14 categorical features, and 0 date-time features.
*   Missing value visualization in `df_train` provided an overview of data completeness across all features.
*   Univariate analysis for numerical features included descriptive statistics, histograms, and box plots, providing insights into their distributions and the presence of outliers.
*   Bivariate analysis of numerical features against 'is_bad_loan' revealed:
    *   Most numerical features (e.g., `loan_amnt`, `int_rate`, `annual_inc`, `dti`) showed a statistically significant difference in means between good and bad loans (p < 0.05).
    *   `chargeoff_within_12_mths` did not show a statistically significant difference (p = 0.1905).
    *   `policy_code` was identified as a constant feature, making t-test results inconclusive.
*   Univariate analysis for categorical features involved value counts and count plots, illustrating the frequency distribution of each category.
*   Bivariate analysis of categorical features against 'is_bad_loan' showed:
    *   All categorical features tested (excluding `loan_status`) had a statistically significant association with 'is_bad_loan' (p < 0.05).
    *   `grade` (Cramér's V: 0.3141) and `sub_grade` (Cramér's V: 0.3213) exhibited a moderate association with loan status.
    *   Other features like `term`, `verification_status`, `zip_code`, `earliest_cr_line`, and `initial_list_status` showed weak associations (Cramér's V between 0.1 and 0.2).
    *   Features like `home_ownership`, `pymnt_plan`, `purpose`, `addr_state`, `application_type`, and `disbursement_method` showed very weak associations (Cramér's V < 0.1).
*   Multicollinearity check among numerical features using VIF led to the removal of:
    *   `policy_code` (constant feature).
    *   `funded_amnt_inv` and `installment` (highly correlated with `loan_amnt`).
    *   `pub_rec` (due to remaining high VIF after initial removals).
    After these removals, all remaining numerical features in `df_train` had VIF values below 5, indicating successful mitigation of multicollinearity.

### Insights or Next Steps

*   The dataset is now prepared with a balanced target variable and properly split into training, validation, and test sets, ready for robust model training and evaluation.
*   Proceed with further feature engineering and selection, focusing on handling missing values (as visualized), transforming highly skewed numerical features, and encoding categorical variables, prioritizing those with moderate to weak associations identified through bivariate analysis.

**Reasoning**:
The first step in building the preprocessing pipeline is to separate the target variable from the features for the train, validation, and test sets. I also need to ensure that the 'loan_status' column, which is highly correlated with the target, is removed from the feature sets.
"""

TARGET = 'is_bad_loan'

# Separate target variable from features
X_train = df_train.drop(columns=[TARGET, 'loan_status'])
y_train = df_train[TARGET]

X_val = df_val.drop(columns=[TARGET, 'loan_status'])
y_val = df_val[TARGET]

X_test = df_test.drop(columns=[TARGET, 'loan_status'])
y_test = df_test[TARGET]

print(f"Shape of X_train: {X_train.shape}, y_train: {y_train.shape}")
print(f"Shape of X_val: {X_val.shape}, y_val: {y_val.shape}")
print(f"Shape of X_test: {X_test.shape}, y_test: {y_test.shape}")

"""**Reasoning**:
As instructed, I will now identify the numerical and categorical features from `X_train` and then define the preprocessing steps for both numerical and categorical features using `SimpleImputer`, `RobustScaler`, and `OneHotEncoder` within a `ColumnTransformer` for the data preprocessing pipeline.


"""

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import RobustScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Identify numerical and categorical features from X_train
# numerical_cols_train was updated after VIF, so it should be used for numerical features
# categorical_cols_train initially included 'loan_status' and TARGET, which are now removed from X_train.
# So, we need to redefine categorical_features based on X_train's dtypes.

numerical_features = X_train.select_dtypes(include=np.number).columns.tolist()
categorical_features = X_train.select_dtypes(include='object').columns.tolist()

print(f"Numerical features identified: {numerical_features}")
print(f"Categorical features identified: {categorical_features}")

# Define preprocessing steps for numerical features
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', RobustScaler())
])

# Define preprocessing steps for categorical features
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Create a ColumnTransformer to apply different transformations to different columns
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])

print("Preprocessing pipeline (ColumnTransformer) created.")

"""**Reasoning**:
I will fit the `preprocessor` on the training data (`X_train`) and then transform the training, validation, and test datasets (`X_train`, `X_val`, `X_test`) to apply the defined imputation, scaling, and encoding steps. Afterwards, I will print the shapes of the processed dataframes for verification.


"""

X_train_processed = preprocessor.fit_transform(X_train)
X_val_processed = preprocessor.transform(X_val)
X_test_processed = preprocessor.transform(X_test)

print(f"Shape of X_train_processed: {X_train_processed.shape}")
print(f"Shape of X_val_processed: {X_val_processed.shape}")
print(f"Shape of X_test_processed: {X_test_processed.shape}")

"""## Baseline Model Training and Evaluation (Logistic Regression)

### Subtask:
Train a baseline Logistic Regression model using the preprocessed df_train. Evaluate its performance on df_val using key metrics such as ROC AUC, Average Precision Score, F1-score, and Brier Score. This will serve as a benchmark for more complex models.

**Reasoning**:
I will create a `Pipeline` that combines the previously defined `preprocessor` with a `LogisticRegression` model, then train this pipeline on the training data and evaluate its performance on the validation set using the specified metrics to establish a baseline.
"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, average_precision_score, f1_score, brier_score_loss
from sklearn.pipeline import Pipeline

# 1. Create a Pipeline named baseline_model
baseline_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(solver='liblinear', random_state=42, n_jobs=-1))
])

# 2. Train the baseline_model
print("Training baseline Logistic Regression model...")
baseline_model.fit(X_train, y_train)
print("Training complete.")

# 3. Predict probabilities for the positive class on the validation set
y_pred_proba_val = baseline_model.predict_proba(X_val)[:, 1]

# 4. Predict class labels on the validation set
y_pred_val = baseline_model.predict(X_val)

# 5. Calculate evaluation metrics
roc_auc = roc_auc_score(y_val, y_pred_proba_val)
avg_precision = average_precision_score(y_val, y_pred_proba_val)
f1 = f1_score(y_val, y_pred_val)
brier_score = brier_score_loss(y_val, y_pred_proba_val)

# 6. Print the calculated evaluation metrics
print("\n--- Baseline Logistic Regression Model Performance on Validation Set ---")
print(f"ROC AUC Score: {roc_auc:.4f}")
print(f"Average Precision Score: {avg_precision:.4f}")
print(f"F1-score: {f1:.4f}")
print(f"Brier Score Loss: {brier_score:.4f}")

"""## Champion Model Training and Hyperparameter Tuning (LightGBM)

### Subtask:
Train a champion LightGBM model. Optimize its hyperparameters using Optuna on the validation set (`df_val`) to maximize performance on a chosen metric (e.g., ROC AUC). Evaluate the optimized champion model's performance on `df_val` and `df_test` and compare it against the baseline.

**Reasoning**:
I will now generate the Python code to implement the champion LightGBM model training and hyperparameter tuning using Optuna, as described in the subtask instructions. This code will define the objective function for Optuna, run the optimization, train the final model, and evaluate its performance on both validation and test sets, then compare it to the baseline model.
"""

import optuna
import lightgbm as lgb
from sklearn.metrics import roc_auc_score, average_precision_score, f1_score, brier_score_loss
from sklearn.pipeline import Pipeline
import warnings

warnings.filterwarnings("ignore", category=UserWarning) # Suppress LightGBM warnings

# Define the objective function for Optuna
def objective(trial):
    # Hyperparameters to tune
    param = {
        'objective': 'binary',
        'metric': 'auc',
        'boosting_type': 'gbdt',
        'n_jobs': -1,
        'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.1),
        'num_leaves': trial.suggest_int('num_leaves', 20, 255),
        'max_depth': trial.suggest_int('max_depth', 5, 15),
        'min_child_samples': trial.suggest_int('min_child_samples', 20, 500),
        'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
        'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),
        'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0),
        'random_state': 42,
        'verbose': -1, # Suppress verbose output during tuning
        'n_estimators': trial.suggest_int('n_estimators', 100, 1000)
    }

    # Create a LightGBM pipeline
    model = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('classifier', lgb.LGBMClassifier(**param))
    ])

    # Train the model
    model.fit(X_train, y_train)

    # Predict probabilities on the validation set
    y_pred_proba_val_objective = model.predict_proba(X_val)[:, 1]

    # Evaluate using ROC AUC score
    roc_auc_objective = roc_auc_score(y_val, y_pred_proba_val_objective)

    return roc_auc_objective

# Create an Optuna study and optimize
print("Starting Optuna hyperparameter tuning for LightGBM...")
study = optuna.create_study(direction='maximize', study_name='lgbm_tuning')
study.optimize(objective, n_trials=50) # You can adjust n_trials for more extensive tuning
print("Hyperparameter tuning complete.")

# Get the best hyperparameters
best_params = study.best_params
print("\nBest hyperparameters found by Optuna:")
print(best_params)

# Train the champion LightGBM model with the best hyperparameters
print("\nTraining champion LightGBM model with best hyperparameters...")
champion_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', lgb.LGBMClassifier(**best_params, random_state=42, n_jobs=-1, verbose=-1))
])
champion_model.fit(X_train, y_train)
print("Champion model training complete.")

# Evaluate the champion model on the validation set
y_pred_proba_val_champion = champion_model.predict_proba(X_val)[:, 1]
y_pred_val_champion = champion_model.predict(X_val)

roc_auc_val_champion = roc_auc_score(y_val, y_pred_proba_val_champion)
avg_precision_val_champion = average_precision_score(y_val, y_pred_proba_val_champion)
f1_val_champion = f1_score(y_val, y_pred_val_champion)
brier_val_champion = brier_score_loss(y_val, y_pred_proba_val_champion)

print("\n--- Champion LightGBM Model Performance on Validation Set ---")
print(f"ROC AUC Score: {roc_auc_val_champion:.4f}")
print(f"Average Precision Score: {avg_precision_val_champion:.4f}")
print(f"F1-score: {f1_val_champion:.4f}")
print(f"Brier Score Loss: {brier_val_champion:.4f}")

# Evaluate the champion model on the test set
y_pred_proba_test_champion = champion_model.predict_proba(X_test)[:, 1]
y_pred_test_champion = champion_model.predict(X_test)

roc_auc_test_champion = roc_auc_score(y_test, y_pred_proba_test_champion)
avg_precision_test_champion = average_precision_score(y_test, y_pred_proba_test_champion)
f1_test_champion = f1_score(y_test, y_pred_test_champion)
brier_test_champion = brier_score_loss(y_test, y_pred_proba_test_champion)

print("\n--- Champion LightGBM Model Performance on Test Set ---")
print(f"ROC AUC Score: {roc_auc_test_champion:.4f}")
print(f"Average Precision Score: {avg_precision_test_champion:.4f}")
print(f"F1-score: {f1_test_champion:.4f}")
print(f"Brier Score Loss: {brier_test_champion:.4f}")

# Compare with baseline (assuming baseline_model and its metrics are still available)
print("\n--- Performance Comparison (Champion LGBM vs. Baseline Logistic Regression) ---")
print(f"Baseline Logistic Regression ROC AUC (Val): {roc_auc:.4f}")
print(f"Champion LightGBM ROC AUC (Val): {roc_auc_val_champion:.4f}")
print(f"Champion LightGBM ROC AUC (Test): {roc_auc_test_champion:.4f}")

best_params =
{'learning_rate': 0.07602133011030703, 'num_leaves': 139, 'max_depth': 13, 'min_child_samples': 48, 'subsample': 0.7711230680041171, 'colsample_bytree': 0.853828548603552, 'reg_alpha': 1.319770029834369, 'reg_lambda': 1.272842611474062e-06, 'n_estimators': 828}

print("\nTraining champion LightGBM model with best hyperparameters...")
champion_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', lgb.LGBMClassifier(**best_params, random_state=42, n_jobs=-1, verbose=-1))
])
champion_model.fit(X_train, y_train)
print("Champion model training complete.")

"""## Model Calibration and Threshold Optimization

### Subtask:
Calibrate the champion model's predicted probabilities using `CalibratedClassifierCV` (Isotonic regression) on the validation set (`df_val`). After calibration, optimize the decision threshold based on a hypothetical business profit/cost matrix to maximize expected profit.

**Reasoning**:
I will start by extracting the LightGBM classifier from the champion model pipeline, as the `CalibratedClassifierCV` needs a classifier object, not the entire pipeline, for calibration. Then I will instantiate `CalibratedClassifierCV` with this classifier using isotonic regression and `cv='prefit'` which fits the calibrator on the already processed validation data. This sets up the calibration process.
"""

from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import confusion_matrix

# 1. Extract the LightGBM classifier from the champion_model pipeline
lgbm_classifier = champion_model.named_steps['classifier']

# 2. Instantiate CalibratedClassifierCV with the extracted lgbm_classifier
#    Use method='isotonic' for isotonic regression and cv='prefit' as we have already split the data
calibrated_lgbm = CalibratedClassifierCV(lgbm_classifier, method='isotonic', cv='prefit')

# Ensure X_val_processed and y_val are ready for fitting
# The preprocessor has already been fitted on X_train and transformed X_val
# So, calibrated_lgbm will be fitted using the probabilities predicted by lgbm_classifier on X_val_processed

# To use cv='prefit', the base estimator (lgbm_classifier) should ideally be fitted on the training data
# and then CalibratedClassifierCV will be fitted on the validation data.
# Our champion_model (which contains lgbm_classifier) is already fitted on X_train.
# So, we just need to fit calibrated_lgbm on X_val_processed and y_val.

# 3. Fit the calibrated_lgbm instance using the preprocessed validation features and true validation labels
print(f"Shape of X_val_processed for calibration: {X_val_processed.shape}")
print(f"Shape of y_val for calibration: {y_val.shape}")
calibrated_lgbm.fit(X_val_processed, y_val)

print("CalibratedClassifierCV fitted on validation set.")

"""**Reasoning**:
Now that the model is calibrated, I will obtain the calibrated probabilities, define the profit/cost matrix, iterate through various thresholds to calculate the expected profit, identify the optimal threshold that maximizes profit, and finally, visualize the expected profit against the thresholds as per the subtask instructions.


"""

import numpy as np
import matplotlib.pyplot as plt

# 4. Obtain calibrated probabilities on the validation set
y_pred_proba_val_calibrated = calibrated_lgbm.predict_proba(X_val_processed)[:, 1]

# 5. Define the profit/cost matrix parameters
profit_tn = 1000  # Correctly approve good loan
cost_fp = -200    # Incorrectly reject good loan (Opportunity Cost)
cost_fn = -5000   # Incorrectly approve bad loan (Default Loss)
profit_tp = 0     # Correctly reject bad loan (Cost Avoidance)

# 6. Generate a range of decision thresholds
thresholds = np.linspace(0, 1, 1000) # 1000 thresholds from 0 to 1

best_threshold = 0.5
max_expected_profit = -np.inf # Initialize with a very small number

profits_per_threshold = []

print("\nOptimizing decision threshold...")
for threshold in thresholds:
    # a. Convert probabilities to binary predictions using the current threshold
    y_pred_val_threshold = (y_pred_proba_val_calibrated >= threshold).astype(int)

    # b. Calculate confusion matrix for the current threshold
    # cm[0,0] = TN (Actual 0, Predicted 0)
    # cm[0,1] = FP (Actual 0, Predicted 1)
    # cm[1,0] = FN (Actual 1, Predicted 0)
    # cm[1,1] = TP (Actual 1, Predicted 1)
    cm = confusion_matrix(y_val, y_pred_val_threshold)

    tn, fp, fn, tp = cm.ravel() if cm.size == 4 else (0, 0, 0, 0) # Handle cases where a class might be empty

    # d. Calculate expected profit for the current threshold
    expected_profit = (tn * profit_tn) + (fp * cost_fp) + (fn * cost_fn) + (tp * profit_tp)
    profits_per_threshold.append(expected_profit)

    # e. Update best threshold if current profit is higher
    if expected_profit > max_expected_profit:
        max_expected_profit = expected_profit
        best_threshold = threshold

print(f"Optimal decision threshold: {best_threshold:.4f}")
print(f"Maximum expected profit at this threshold: ${max_expected_profit:,.2f}")

# 8. Plot the expected profit vs. threshold
plt.figure(figsize=(10, 6))
plt.plot(thresholds, profits_per_threshold, label='Expected Profit')
plt.axvline(best_threshold, color='r', linestyle='--', label=f'Optimal Threshold: {best_threshold:.4f}')
plt.title('Expected Profit vs. Decision Threshold')
plt.xlabel('Threshold')
plt.ylabel('Expected Profit')
plt.grid(True)
plt.legend()
plt.show()

"""**Reasoning**:
Now that the optimal threshold has been determined, I will evaluate the calibrated champion model's performance on both the validation and test sets using this optimal threshold. This involves calculating ROC AUC, Average Precision Score, F1-score, and Brier Score for each set and printing the results for comparison.


"""

from sklearn.metrics import roc_auc_score, average_precision_score, f1_score, brier_score_loss

# Evaluate champion model on validation set using the optimal threshold
# We already have y_pred_proba_val_calibrated from the previous step
y_pred_val_optimal_threshold = (y_pred_proba_val_calibrated >= best_threshold).astype(int)

# Re-calculate evaluation metrics for validation set with optimal threshold
roc_auc_val_calibrated = roc_auc_score(y_val, y_pred_proba_val_calibrated)
avg_precision_val_calibrated = average_precision_score(y_val, y_pred_proba_val_calibrated)
f1_val_optimal = f1_score(y_val, y_pred_val_optimal_threshold)
brier_val_calibrated = brier_score_loss(y_val, y_pred_proba_val_calibrated)

print("\n--- Calibrated Champion LightGBM Model Performance on Validation Set (Optimal Threshold) ---")
print(f"ROC AUC Score (Calibrated Prob): {roc_auc_val_calibrated:.4f}")
print(f"Average Precision Score (Calibrated Prob): {avg_precision_val_calibrated:.4f}")
print(f"F1-score (Optimal Threshold): {f1_val_optimal:.4f}")
print(f"Brier Score Loss (Calibrated Prob): {brier_val_calibrated:.4f}")

# Obtain calibrated probabilities for the test set
X_test_processed = preprocessor.transform(X_test) # Ensure X_test is processed if not done in previous step
y_pred_proba_test_calibrated = calibrated_lgbm.predict_proba(X_test_processed)[:, 1]
y_pred_test_optimal_threshold = (y_pred_proba_test_calibrated >= best_threshold).astype(int)

# Re-calculate evaluation metrics for test set with optimal threshold
roc_auc_test_calibrated = roc_auc_score(y_test, y_pred_proba_test_calibrated)
avg_precision_test_calibrated = average_precision_score(y_test, y_pred_proba_test_calibrated)
f1_test_optimal = f1_score(y_test, y_pred_test_optimal_threshold)
brier_test_calibrated = brier_score_loss(y_test, y_pred_proba_test_calibrated)

print("\n--- Calibrated Champion LightGBM Model Performance on Test Set (Optimal Threshold) ---")
print(f"ROC AUC Score (Calibrated Prob): {roc_auc_test_calibrated:.4f}")
print(f"Average Precision Score (Calibrated Prob): {avg_precision_test_calibrated:.4f}")
print(f"F1-score (Optimal Threshold): {f1_test_optimal:.4f}")
print(f"Brier Score Loss (Calibrated Prob): {brier_test_calibrated:.4f}")

"""# Task
* **Prepare Processed Data for SHAP**: Explicitly convert the `X_train_processed` sparse matrix (output from `preprocessor.transform`) into a dense NumPy array. Then, construct the full list of `processed_feature_names` by combining the original numerical feature names and the one-hot encoded categorical feature names obtained from the `preprocessor`. Finally, create a Pandas DataFrame (`X_train_processed_df`) using this dense array and the correct feature names. This robust conversion is critical for accurate SHAP calculations and plot generation.
* **Sample Processed Data for SHAP**: Take a stratified 10% sample (15,000 rows) of the `X_train_processed_df` DataFrame, along with the corresponding `y_train` labels, ensuring that the class distribution of 'is_bad_loan' is maintained in the sample. This sampled data (`X_train_shap_sample`, `y_train_shap_sample`) will be used for all subsequent SHAP calculations to manage computational resources efficiently.
* **Calculate and Visualize Global SHAP Values**: Initialize a SHAP `TreeExplainer` with the trained LightGBM classifier (`calibrated_lgbm.base_estimator`). Calculate SHAP values for the positive class using the `X_train_shap_sample`. Generate global SHAP summary plots (both bar and beeswarm types) to visualize the overall feature importance and their impact direction on the model's predictions.
* **Generate Local SHAP Explanations (Force Plots)**: Identify specific instances from the `X_train_shap_sample` that represent different prediction scenarios: correctly predicted good loans, correctly predicted bad loans, mispredicted good loans (false positives), and mispredicted bad loans (false negatives). For each of these selected instances, calculate and display local SHAP force plots to provide detailed, individual reason codes for the model's prediction.
* **Fairness Analysis and Mitigation**: Conduct a thorough fairness analysis. Identify sensitive attributes (if available and relevant, based on legal/ethical considerations). Evaluate fairness metrics such as Disparate Impact (DP) and Equal Opportunity (EO) across different demographic groups using the `fairlearn` library. Investigate and apply mitigation techniques like reject-option classification or group-specific threshold optimization to address identified biases.
* **Inference System Development**: Develop a robust inference utility. This will be a Python function that accepts a dictionary of new applicant parameters (defined by the features deemed important during EDA and feature selection), applies the trained preprocessing pipeline, and uses the calibrated champion model to predict a loan decision (approve/reject) along with the probability of default (PD). Additionally, it will provide the top reasons for the decision using local SHAP explanations.
* **Artifact Persistence**: Save all trained models (baseline and champion), the complete preprocessing pipeline, feature lists, and any necessary mapping dictionaries using `joblib`. This ensures that all critical components of the system can be easily reloaded and reused for future inferences or analyses without retraining.
* **Final Task**: Summarize the implemented Advanced Credit Decisioning System, highlighting its key components, performance, explainability, and fairness considerations.

## Prepare Processed Data for SHAP

### Subtask:
Explicitly convert the `X_train_processed` sparse matrix (output from `preprocessor.transform`) into a dense NumPy array. Then, construct the full list of `processed_feature_names` by combining the original numerical feature names and the one-hot encoded categorical feature names obtained from the `preprocessor`. Finally, create a Pandas DataFrame (`X_train_processed_df`) using this dense array and the correct feature names. This robust conversion is critical for accurate SHAP calculations and plot generation.

**Reasoning**:
The subtask requires converting the sparse processed data to a dense DataFrame with correct feature names for SHAP analysis. This code block performs all necessary steps: converting to dense array, getting feature names for numerical and one-hot encoded categorical features, combining them, and finally creating the DataFrame with the original index.
"""

import pandas as pd
import numpy as np

# 1. Convert the sparse matrix X_train_processed into a dense NumPy array
X_train_processed_dense = X_train_processed.toarray()

# 2. Obtain the list of feature names for the numerical features (already available)
numerical_feature_names = numerical_features

# 3. Extract the one-hot encoded feature names for the categorical features
categorical_feature_names = preprocessor.named_transformers_['cat'].named_steps['onehot'].get_feature_names_out(categorical_features)

# 4. Combine the numerical feature names and the one-hot encoded categorical feature names
processed_feature_names = numerical_feature_names + categorical_feature_names.tolist()

# 5. Create a new Pandas DataFrame called X_train_processed_df
X_train_processed_df = pd.DataFrame(
    X_train_processed_dense,
    columns=processed_feature_names,
    index=X_train.index # Ensure the index matches the original X_train DataFrame
)

print(f"Shape of X_train_processed_df: {X_train_processed_df.shape}")
print("First 5 rows of X_train_processed_df:")
display(X_train_processed_df.head())

"""**Reasoning**:
The next step is to create a stratified sample of the processed training data (`X_train_processed_df`) and its corresponding target variable (`y_train`) for SHAP analysis, as required by the subtask. This ensures that the class distribution is maintained in the sample, which is important for accurate SHAP calculations, and manages computational resources by using a smaller subset.


"""

from sklearn.model_selection import train_test_split

# Calculate the desired sample size (10% of X_train_processed_df)
# X_train_processed_df has 150,000 rows, so 10% is 15,000 rows.
# Note: train_test_split expects test_size as a fraction or absolute number of samples.

# Perform stratified sampling, taking 10% of the data for SHAP
_, X_train_shap_sample, _, y_train_shap_sample = train_test_split(
    X_train_processed_df,
    y_train, # Use y_train directly, as it's already aligned with X_train_processed_df by sample count
    test_size=0.10, # 10% of the original df_train (150,000 rows) which is 15,000 rows
    stratify=y_train, # Use y_train directly for stratification
    random_state=42
)

print(f"Shape of X_train_shap_sample: {X_train_shap_sample.shape}")
print(f"Shape of y_train_shap_sample: {y_train_shap_sample.shape}")

print("\nDistribution of 'is_bad_loan' in y_train_shap_sample:")
print(y_train_shap_sample.value_counts())
print((y_train_shap_sample.value_counts() / len(y_train_shap_sample) * 100).round(2))

"""## Calculate and Visualize Global SHAP Values

### Subtask:
Initialize a SHAP `TreeExplainer` with the trained LightGBM classifier (`calibrated_lgbm.base_estimator`). Calculate SHAP values for the positive class using the `X_train_shap_sample`. Generate global SHAP summary plots (both bar and beeswarm types) to visualize the overall feature importance and their impact direction on the model's predictions.

**Reasoning**:
The previous code failed because `shap_values` was already the 2D array for the positive class, and indexing it with `[1]` resulted in a 1D vector. I will fix this by directly passing the `shap_values` (the output of `explainer.shap_values`) to `shap.summary_plot`, which expects a 2D array (matrix).
"""

import shap
import matplotlib.pyplot as plt

# 1. Initialize a SHAP TreeExplainer
# calibrated_lgbm.estimator refers to the underlying LGBMClassifier
explainer = shap.TreeExplainer(calibrated_lgbm.estimator)

# 2. Calculate SHAP values for the positive class
# Based on the kernel state and traceback, explainer.shap_values returns the 2D array directly
# for the positive class for this specific setup/model.
shap_values = explainer.shap_values(X_train_shap_sample)

# 3. Generate a SHAP summary bar plot
print("\nGenerating SHAP summary bar plot...")
shap.summary_plot(shap_values, X_train_shap_sample, plot_type='bar', show=False)
plt.title('Global Feature Importance (SHAP - Bar Plot)')
plt.show()

# 4. Generate a SHAP summary beeswarm plot
print("\nGenerating SHAP summary beeswarm plot...")
shap.summary_plot(shap_values, X_train_shap_sample, show=False)
plt.title('Global Feature Importance (SHAP - Beeswarm Plot)')
plt.show()

"""**Reasoning**:
Now that the global SHAP values have been visualized, I will proceed to generate local SHAP explanations. This involves identifying specific instances from the `X_train_shap_sample` that represent different prediction scenarios (correctly predicted good/bad loans, mispredicted good/bad loans) and then calculating and displaying local SHAP force plots for each instance to understand individual prediction contributions.


"""

from sklearn.metrics import confusion_matrix
import numpy as np
import pandas as pd # Ensure pandas is imported

# Get predictions from the calibrated model on the SHAP sample
y_pred_proba_shap_sample_calibrated = calibrated_lgbm.predict_proba(X_train_shap_sample)[:, 1]
y_pred_shap_sample_optimal_threshold = (y_pred_proba_shap_sample_calibrated >= best_threshold).astype(int)

# Create a DataFrame for easier indexing and filtering
shap_results = pd.DataFrame({
    'y_true': y_train_shap_sample,
    'y_pred': y_pred_shap_sample_optimal_threshold
}, index=X_train_shap_sample.index)

# Identify indices for different prediction scenarios
true_negatives_idx = shap_results[(shap_results['y_true'] == False) & (shap_results['y_pred'] == 0)].index
true_positives_idx = shap_results[(shap_results['y_true'] == True) & (shap_results['y_pred'] == 1)].index
false_positives_idx = shap_results[(shap_results['y_true'] == False) & (shap_results['y_pred'] == 1)].index
false_negatives_idx = shap_results[(shap_results['y_true'] == True) & (shap_results['y_pred'] == 0)].index

print(f"Number of True Negatives: {len(true_negatives_idx)}")
print(f"Number of True Positives: {len(true_positives_idx)}")
print(f"Number of False Positives: {len(false_positives_idx)}")
print(f"Number of False Negatives: {len(false_negatives_idx)}")

# Select one instance from each category for force plots
def get_sample_for_shap(idx_list, X_data):
    if len(idx_list) > 0:
        random_idx = np.random.choice(idx_list.to_numpy(), 1).item()
        # Return a DataFrame slice with a single row to keep feature names
        return X_data.loc[[random_idx]]
    # Return an empty DataFrame with correct columns if no samples
    return pd.DataFrame(columns=X_data.columns)

tn_sample = get_sample_for_shap(true_negatives_idx, X_train_shap_sample)
tp_sample = get_sample_for_shap(true_positives_idx, X_train_shap_sample)
fp_sample = get_sample_for_shap(false_positives_idx, X_train_shap_sample)
fn_sample = get_sample_for_shap(false_negatives_idx, X_train_shap_sample)

# Generate SHAP force plots
print("\nGenerating Local SHAP Explanations (Force Plots)...")

# explainer is already defined in the previous cell

if not tn_sample.empty:
    print("\nForce Plot for a Correctly Predicted Good Loan (True Negative):")
    shap.initjs()
    tn_shap_values = explainer.shap_values(tn_sample)
    # Access the first (and only) row of SHAP values, and pass the instance's first row as a Series
    shap.force_plot(explainer.expected_value, tn_shap_values[0], tn_sample.iloc[0], matplotlib=True, show=False)
    plt.title('True Negative Instance Explanation')
    plt.show()

if not tp_sample.empty:
    print("\nForce Plot for a Correctly Predicted Bad Loan (True Positive):")
    shap.initjs()
    tp_shap_values = explainer.shap_values(tp_sample)
    # Access the first (and only) row of SHAP values, and pass the instance's first row as a Series
    shap.force_plot(explainer.expected_value, tp_shap_values[0], tp_sample.iloc[0], matplotlib=True, show=False)
    plt.title('True Positive Instance Explanation')
    plt.show()

if not fp_sample.empty:
    print("\nForce Plot for a Mispredicted Good Loan (False Positive):")
    shap.initjs()
    fp_shap_values = explainer.shap_values(fp_sample)
    # Access the first (and only) row of SHAP values, and pass the instance's first row as a Series
    shap.force_plot(explainer.expected_value, fp_shap_values[0], fp_sample.iloc[0], matplotlib=True, show=False)
    plt.title('False Positive Instance Explanation')
    plt.show()

if not fn_sample.empty:
    print("\nForce Plot for a Mispredicted Bad Loan (False Negative):")
    shap.initjs()
    fn_shap_values = explainer.shap_values(fn_sample)
    # Access the first (and only) row of SHAP values, and pass the instance's first row as a Series
    shap.force_plot(explainer.expected_value, fn_shap_values[0], fn_sample.iloc[0], matplotlib=True, show=False)
    plt.title('False Negative Instance Explanation')
    plt.show()

"""**Reasoning**:
Now that local SHAP explanations have been generated, I will proceed with fairness analysis. I'll start by identifying 'addr_state' as a sensitive attribute from the original `X_test` dataset. Then, I'll evaluate fairness metrics, specifically disparate impact and equal opportunity, using the `fairlearn` library to understand potential biases across different states in the test set. This requires using the predictions from the calibrated champion model on the test data.


"""

from fairlearn.metrics import (MetricFrame, selection_rate, true_positive_rate)

# Identify the sensitive attribute
sensitive_attribute = X_test['addr_state']

# Ensure the predictions are aligned with the sensitive attribute
# y_pred_test_optimal_threshold and y_pred_proba_test_calibrated are already calculated for X_test

print("\n--- Fairness Analysis using 'addr_state' as Sensitive Attribute ---")

# 1. Disparate Impact (Selection Rate)
# Selection rate is the proportion of individuals for whom the model predicts a positive outcome (approves loan).
# Disparate Impact is often calculated as the ratio of selection rates between unprivileged and privileged groups.
# A ratio significantly different from 1 (e.g., < 0.8 or > 1.25) can indicate disparate impact.

# Calculate selection rate for each group
selection_rate_per_group = MetricFrame(metrics=selection_rate, y_true=y_test,
                                     y_pred=y_pred_test_optimal_threshold, sensitive_features=sensitive_attribute)

print("\nSelection Rate per 'addr_state' Group:")
display(selection_rate_per_group.by_group)

# To get an overall sense of disparate impact, we can look at the ratio of min to max selection rates
min_selection_rate = selection_rate_per_group.by_group.min()
max_selection_rate = selection_rate_per_group.by_group.max()

disparate_impact_ratio = min_selection_rate / max_selection_rate if max_selection_rate != 0 else np.nan

print(f"\nDisparate Impact Ratio (Min/Max Selection Rate): {disparate_impact_ratio:.4f}")
if disparate_impact_ratio < 0.8 or disparate_impact_ratio > 1.25:
    print("  Interpretation: Potential disparate impact detected (ratio significantly different from 1). Decision rates vary substantially across states.")
else:
    print("  Interpretation: No significant disparate impact detected based on min/max ratio.")

# 2. Equal Opportunity (True Positive Rate)
# True Positive Rate (Recall) is the proportion of actual positive outcomes that are correctly predicted as positive.
# Equal Opportunity is achieved if the True Positive Rate is equal across different groups.

# Calculate true positive rate for each group
true_positive_rate_per_group = MetricFrame(metrics=true_positive_rate, y_true=y_test,
                                          y_pred=y_pred_test_optimal_threshold, sensitive_features=sensitive_attribute)

print("\nTrue Positive Rate per 'addr_state' Group (Equal Opportunity):")
display(true_positive_rate_per_group.by_group)

# To get an overall sense of equal opportunity, we can look at the ratio of min to max TPR
min_tpr = true_positive_rate_per_group.by_group.min()
max_tpr = true_positive_rate_per_group.by_group.max()

equal_opportunity_ratio = min_tpr / max_tpr if max_tpr != 0 else np.nan

print(f"\nEqual Opportunity Ratio (Min/Max True Positive Rate): {equal_opportunity_ratio:.4f}")
if equal_opportunity_ratio < 0.8 or equal_opportunity_ratio > 1.25:
    print("  Interpretation: Potential unequal opportunity detected (ratio significantly different from 1). True Positive Rates vary substantially across states.")
else:
    print("  Interpretation: No significant unequal opportunity detected based on min/max ratio.")

# Note: Fairlearn's mitigation strategies like ExponentiatedGradient or GridSearch can be applied
# if significant unfairness is detected.

"""# Task
Develop an Advanced Credit Decisioning System. This involves loading and cleaning the "loan.csv" dataset from `/root/.cache/kagglehub/datasets/adarshsng/lending-club-loan-data-csv/versions/1/loan.csv`, performing comprehensive exploratory data analysis, preparing the data through resampling and stratification, training and evaluating baseline (Logistic Regression) and champion (LightGBM with Optuna tuning) models, calibrating the champion model and optimizing the decision threshold based on a profit/cost matrix, and conducting fairness analysis using Fairlearn. Finally, develop an inference utility that predicts loan decisions and probabilities of default for new applicants, provides local SHAP explanations (with corrected example usage for flat applicant dictionaries), and ensure all trained models, preprocessing pipelines, and relevant artifacts are persisted using `joblib`.

## Inference System Development

### Subtask:
Develop a robust inference utility. This will be a Python function that accepts a dictionary of new applicant parameters (defined by the features deemed important during EDA and feature selection), applies the trained preprocessing pipeline, and uses the calibrated champion model to predict a loan decision (approve/reject) along with the probability of default (PD). Additionally, it will provide the top reasons for the decision using local SHAP explanations. The example usage will be corrected to ensure dummy applicant data is correctly formatted as flat dictionaries.
"""

import pandas as pd
import numpy as np
import shap
import matplotlib.pyplot as plt

# Define the inference system function
def inference_system(applicant_data: dict, preprocessor, calibrated_model, shap_explainer, best_threshold, top_n_features=5):
    """
    Predicts loan decision and probability of default for a new applicant,
    and provides local SHAP explanations.

    Args:
        applicant_data (dict): A dictionary of new applicant parameters.
        preprocessor: The fitted ColumnTransformer preprocessing pipeline.
        calibrated_model: The fitted CalibratedClassifierCV model.
        shap_explainer: The fitted SHAP TreeExplainer.
        best_threshold (float): The optimal decision threshold.
        top_n_features (int): Number of top SHAP features to display.

    Returns:
        dict: A dictionary containing prediction, probability of default, and SHAP explanations.
    """

    # 1. Create a DataFrame from applicant_data
    # Ensure the order of columns matches X_train before preprocessing
    X_train_cols = X_train.columns.tolist()
    input_df = pd.DataFrame([applicant_data], columns=X_train_cols)

    # 2. Apply the trained preprocessing pipeline
    processed_input = preprocessor.transform(input_df)

    # Convert processed_input sparse matrix to dense DataFrame for SHAP explanation
    # Re-extract feature names as they might be stale if notebook was restarted
    numerical_features_inference = X_train.select_dtypes(include=np.number).columns.tolist()
    categorical_features_inference = X_train.select_dtypes(include='object').columns.tolist()

    # Get one-hot encoded feature names directly from the fitted OneHotEncoder
    ohe_feature_names = preprocessor.named_transformers_['cat'].named_steps['onehot'].get_feature_names_out(categorical_features_inference)
    processed_feature_names_inference = numerical_features_inference + ohe_feature_names.tolist()

    processed_input_df = pd.DataFrame(
        processed_input.toarray(),
        columns=processed_feature_names_inference
    )

    # 3. Use the calibrated champion model to predict PD and decision
    prob_default = calibrated_model.predict_proba(processed_input)[:, 1][0]
    decision = 'Reject' if prob_default >= best_threshold else 'Approve'

    # 4. Provide top reasons using local SHAP explanations
    # Pass a single-row DataFrame (iloc[[0]]) to explainer.shap_values
    shap_values_output = shap_explainer.shap_values(processed_input_df.iloc[[0]])

    # Correctly extract shap_values for the positive class (index 1)
    if isinstance(shap_values_output, list):
        # For TreeExplainer, shap_values returns a list of arrays for multi-class, or a single array for binary
        # Our model is binary, so we might get a list [shap_values_for_class_0, shap_values_for_class_1]
        # Or directly shap_values_for_class_1 if the model structure is different
        if len(shap_values_output) == 2:
            shap_values_instance = shap_values_output[1][0] # Class 1 SHAP values, first instance
        else: # Handle cases where it might return just one array for the positive class
            shap_values_instance = shap_values_output[0]
    else: # If shap_values_output is directly the 2D array for the positive class
        shap_values_instance = shap_values_output[0]

    expected_value_for_plot = shap_explainer.expected_value


    # Create a DataFrame for SHAP values and sort by absolute magnitude
    shap_df = pd.DataFrame({
        'feature': processed_feature_names_inference,
        'shap_value': shap_values_instance
    }).sort_values(by='shap_value', ascending=False, key=abs)

    # Get top N features contributing to the prediction
    top_shap_features = shap_df.head(top_n_features)
    explanation = top_shap_features.to_dict(orient='records')

    # Generate a local SHAP force plot
    print(f"\nSHAP Force Plot for this {decision} decision:")
    shap.initjs()
    # processed_input_df.iloc[0] (Series) is correct for the instance values in force_plot
    shap.force_plot(expected_value_for_plot, shap_values_instance, processed_input_df.iloc[0], matplotlib=True, show=False)
    plt.title(f'Local Explanation for {decision} (PD: {prob_default:.4f})')
    plt.show()


    return {
        'loan_decision': decision,
        'probability_of_default': prob_default,
        'top_shap_reasons': explanation
    }

# --- Corrected Example Usage ---

# 1. Create dummy_applicant_approved by taking the first row of X_train and converting it to a dictionary.
dummy_applicant_approved = X_train.iloc[0].to_dict()

# 2. Create dummy_applicant_rejected by selecting a random index from true_positives_idx
#    and converting the corresponding row from X_train to a dictionary.

# Ensure true_positives_idx is not empty
if len(true_positives_idx) > 0:
    random_rejected_index = np.random.choice(true_positives_idx.to_numpy())
    # Get the row as a Series and convert to a flat dictionary
    # Using .loc[[idx]].iloc[0].to_dict() to ensure a flat dictionary output
    dummy_applicant_rejected = X_train.loc[[random_rejected_index]].iloc[0].to_dict()
else:
    print("Warning: No True Positives found to create a rejected applicant example. Using first row of X_train.")
    dummy_applicant_rejected = X_train.iloc[0].to_dict()

print("\n--- Inference for an Approved-like Applicant ---")
prediction_approved = inference_system(dummy_applicant_approved, preprocessor, calibrated_lgbm, explainer, best_threshold)
print(prediction_approved)

print("\n--- Inference for a Rejected-like Applicant ---")
prediction_rejected = inference_system(dummy_applicant_rejected, preprocessor, calibrated_lgbm, explainer, best_threshold)
print(prediction_rejected)

"""**Reasoning**:
The next step is to save all trained models, the preprocessing pipeline, and other critical artifacts using `joblib.dump` to ensure persistence and reusability, as specified in the subtask.


"""

import joblib
import os

# Define a directory to save artifacts
output_dir = 'model_artifacts'
os.makedirs(output_dir, exist_ok=True)

print(f"Saving artifacts to: {output_dir}/")

# 1. Save the baseline model (Logistic Regression Pipeline)
joblib.dump(baseline_model, os.path.join(output_dir, 'baseline_logistic_regression_pipeline.joblib'))
print("Baseline Logistic Regression Pipeline saved.")

# 2. Save the champion model (LightGBM Pipeline)
joblib.dump(champion_model, os.path.join(output_dir, 'champion_lightgbm_pipeline.joblib'))
print("Champion LightGBM Pipeline saved.")

# 3. Save the calibrated champion model
joblib.dump(calibrated_lgbm, os.path.join(output_dir, 'calibrated_lightgbm_model.joblib'))
print("Calibrated LightGBM Model saved.")

# 4. Save the complete preprocessing pipeline
joblib.dump(preprocessor, os.path.join(output_dir, 'preprocessing_pipeline.joblib'))
print("Preprocessing Pipeline saved.")

# 5. Save the SHAP explainer (if it's not too large/picklable)
# Note: SHAP explainer might be large or not directly picklable in all contexts.
# For TreeExplainer, saving the underlying model is often sufficient, and the explainer can be re-initialized.
# However, for completeness as requested, we attempt to save it.
try:
    joblib.dump(explainer, os.path.join(output_dir, 'shap_explainer.joblib'))
    print("SHAP TreeExplainer saved.")
except Exception as e:
    print(f"Could not save SHAP TreeExplainer: {e}")

# 6. Save numerical and categorical feature lists
joblib.dump(numerical_features, os.path.join(output_dir, 'numerical_features.joblib'))
joblib.dump(categorical_features, os.path.join(output_dir, 'categorical_features.joblib'))
print("Feature lists saved.")

# 7. Save the best decision threshold
joblib.dump(best_threshold, os.path.join(output_dir, 'optimal_decision_threshold.joblib'))
print("Optimal Decision Threshold saved.")

# 8. Save the list of feature columns used for inference input
joblib.dump(X_train.columns.tolist(), os.path.join(output_dir, 'X_train_columns_for_inference.joblib'))
print("X_train columns for inference saved.")

print("All specified artifacts have been saved.")

"""## Advanced Credit Decisioning System: Summary

This notebook develops a comprehensive Advanced Credit Decisioning System, leveraging machine learning techniques for robust loan default prediction. The system incorporates data preparation, model training, hyperparameter tuning, model calibration, decision threshold optimization, explainability, and fairness analysis. All critical components are persisted for reusability.

### Key Components and Workflow:

1.  **Data Ingestion and Initial Cleaning**: The Lending Club loan dataset was loaded, and initial cleaning steps were performed, including handling columns with high missing percentages and dropping columns identified as data leakage.

2.  **Target Variable Creation and Resampling**: A binary target variable `is_bad_loan` was created. The dataset was then stratified and sampled to create `df_sampled`, followed by **resampling** (`df_resampled`) to achieve a balanced class distribution of approximately 65% good loans and 35% bad loans.

3.  **Train-Validation-Test Split**: The `df_resampled` was meticulously split into `df_train` (75%), `df_val` (15%), and `df_test` (10%), with stratification to maintain class balance across all sets.

4.  **Exploratory Data Analysis (EDA)**:
    *   **Univariate Analysis**: Numerical features were analyzed using descriptive statistics, histograms, and box plots to understand distributions and identify outliers. Categorical features were analyzed with value counts and count plots.
    *   **Bivariate Analysis**: Relationships between features and the `is_bad_loan` target were explored. Box plots and t-tests were used for numerical features, while stacked bar charts, Chi-square tests, and Cramér's V were used for categorical features.
    *   **Multicollinearity Check**: Variance Inflation Factor (VIF) was used to identify and address multicollinearity among numerical features, leading to the removal of `policy_code`, `funded_amnt_inv`, `installment`, and `pub_rec`.

5.  **Preprocessing Pipeline**: A `ColumnTransformer` was built to handle numerical and categorical features:
    *   **Numerical**: `SimpleImputer` (median) and `RobustScaler`.
    *   **Categorical**: `SimpleImputer` (most frequent) and `OneHotEncoder`.

6.  **Model Training and Evaluation**: Two models were trained:
    *   **Baseline Model**: Logistic Regression, serving as a performance benchmark.
    *   **Champion Model**: LightGBM, with hyperparameters tuned using Optuna on the validation set to maximize ROC AUC.

7.  **Model Calibration and Threshold Optimization**: The champion LightGBM model was calibrated using `CalibratedClassifierCV` (isotonic regression) on the validation set. An optimal decision threshold was determined by maximizing expected profit based on a predefined business profit/cost matrix.

8.  **Explainability (SHAP)**:
    *   Global SHAP values were calculated and visualized (bar and beeswarm plots) to understand overall feature importance.
    *   Local SHAP force plots were generated for individual predictions (True Negatives, True Positives, False Positives, False Negatives) to provide specific reasons for loan approval or rejection.

9.  **Fairness Analysis**: The `fairlearn` library was used to assess fairness with `addr_state` as a sensitive attribute, evaluating disparate impact (selection rate) and equal opportunity (True Positive Rate) across different states.

10. **Inference System**: A robust Python function (`inference_system`) was developed to simulate real-world loan applications. It accepts new applicant data, applies the full preprocessing pipeline, predicts the loan decision (Approve/Reject) and probability of default (PD) using the calibrated champion model, and provides local SHAP explanations for the decision.

11. **Artifact Persistence**: All trained models (baseline, champion, calibrated champion), the preprocessing pipeline, SHAP explainer, feature lists, and the optimal decision threshold were saved using `joblib` to ensure the system is reproducible and deployable.

### Performance Highlights:

*   **Baseline Logistic Regression (Validation)**: ROC AUC: 0.7440, Average Precision: 0.5819, F1-score: 0.4804, Brier Score: 0.1908.
*   **Champion LightGBM (Validation)**: ROC AUC: 0.9134, Average Precision: 0.8455, F1-score: 0.7655, Brier Score: 0.1206.
*   **Calibrated Champion LightGBM (Validation, Optimal Threshold)**: ROC AUC: 0.9141, Average Precision: 0.8415, F1-score: 0.7558, Brier Score: 0.1108.
*   **Calibrated Champion LightGBM (Test, Optimal Threshold)**: ROC AUC: 0.9113, Average Precision: 0.8349, F1-score: 0.7527, Brier Score: 0.1129.
*   The champion LightGBM model significantly outperforms the baseline, demonstrating strong predictive capabilities.
*   The optimal decision threshold of 0.1902 yields a maximum expected profit of $8,743,000.00.

### Explainability and Fairness Considerations:

*   SHAP values provide crucial insights into feature importance, both globally (which features generally drive predictions) and locally (why a specific loan application was approved or rejected).
*   Fairness analysis revealed potential disparate impact (ratio: 0.4099) and unequal opportunity (ratio: 0.7778) across different `addr_state` groups, indicating that decision rates and True Positive Rates vary. This highlights areas for further investigation and potential mitigation strategies to ensure equitable outcomes.

This system provides a robust and transparent framework for credit decisioning, balancing performance with interpretability and fairness considerations.

## Final Task

### Subtask:
Summarize the implemented Advanced Credit Decisioning System, highlighting its key components, performance, explainability, and fairness considerations.

## Summary:

### Q&A
The implemented Advanced Credit Decisioning System is a comprehensive machine learning framework for loan default prediction. It comprises:
*   **Key Components**: Data preprocessing (imputation, scaling, one-hot encoding), stratified resampling for class balance, model training with Logistic Regression (baseline) and LightGBM (champion, tuned with Optuna), model calibration (CalibratedClassifierCV with isotonic regression), decision threshold optimization based on a profit/cost matrix, explainability using SHAP (global and local), fairness analysis with Fairlearn, and a robust inference system. All artifacts are persisted for reusability.
*   **Performance**: The champion LightGBM model significantly outperformed the baseline, achieving a ROC AUC of 0.9134 on the validation set and 0.9113 on the test set, compared to the baseline Logistic Regression's 0.7440 ROC AUC. The optimal decision threshold of 0.1902 maximized expected profit to \$8,743,000.00.
*   **Explainability**: SHAP values were extensively used to provide insights into feature importance, both globally (bar and beeswarm plots) and locally (force plots) for individual predictions, enhancing the system's transparency.
*   **Fairness Considerations**: Fairlearn identified potential biases across different `addr_state` groups, showing a disparate impact ratio of 0.4099 (selection rate) and an unequal opportunity ratio of 0.7778 (True Positive Rate).

### Data Analysis Key Findings
*   The champion LightGBM model demonstrated superior predictive performance with a ROC AUC of 0.9141 on the validation set and 0.9113 on the test set, significantly outperforming the baseline Logistic Regression (ROC AUC of 0.7440 on validation).
*   An optimal decision threshold of 0.1902 was determined through profit maximization, leading to an estimated maximum expected profit of \$8,743,000.00.
*   The inference system successfully predicts loan decisions and probabilities of default, providing local SHAP explanations, and correctly handles new applicant data formatted as flat dictionaries.
*   Fairness analysis indicated potential bias with a disparate impact ratio of 0.4099 and an unequal opportunity ratio of 0.7778 across different `addr_state` groups.
*   All essential model artifacts, including the baseline and champion models, the calibrated champion model, the preprocessing pipeline, SHAP explainer, feature lists, and the optimal decision threshold, were successfully saved using `joblib`.

### Insights or Next Steps
*   **Mitigate Fairness Biases**: Further investigate the identified disparate impact and unequal opportunity concerning `addr_state` to develop and implement targeted mitigation strategies that ensure a more equitable credit decisioning process.
*   **Deploy and Monitor**: Deploy the persisted model artifacts and the inference system into a production environment, establishing continuous monitoring for model performance, data drift, and fairness metrics to maintain long-term reliability and ethical standards.
"""







"""## Deployable Inference System Entry Point

**Reasoning**:
This section provides a standalone entry point for the inference system after a runtime restart. It demonstrates how to load all necessary artifacts (`preprocessor`, `calibrated_lgbm`, `shap_explainer`, `best_threshold`, and `X_train_columns`) from the saved `model_artifacts` directory. Once loaded, it defines and uses the `inference_system` function to make predictions and provide explanations for new applicant data. This ensures that the model can be used efficiently without re-running the entire notebook.

"""

import joblib
import os
import pandas as pd
import numpy as np
import shap
import matplotlib.pyplot as plt
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import RobustScaler, OneHotEncoder
from sklearn.calibration import CalibratedClassifierCV
import lightgbm as lgb

# Define the directory where artifacts are saved
output_dir = 'model_artifacts'

print(f"Loading artifacts from: {output_dir}/")

# Load the artifacts
try:
    preprocessor = joblib.load(os.path.join(output_dir, 'preprocessing_pipeline.joblib'))
    calibrated_lgbm = joblib.load(os.path.join(output_dir, 'calibrated_lightgbm_model.joblib'))
    explainer = joblib.load(os.path.join(output_dir, 'shap_explainer.joblib'))
    best_threshold = joblib.load(os.path.join(output_dir, 'optimal_decision_threshold.joblib'))
    X_train_columns = joblib.load(os.path.join(output_dir, 'X_train_columns_for_inference.joblib'))
    numerical_features = joblib.load(os.path.join(output_dir, 'numerical_features.joblib'))
    categorical_features = joblib.load(os.path.join(output_dir, 'categorical_features.joblib'))
    print("All artifacts loaded successfully.")
except Exception as e:
    print(f"Error loading artifacts: {e}. Please ensure the 'Artifact Persistence' cell has been run.")
    # Exit or handle error as appropriate

# Re-define the inference_system function (copy-pasted for standalone nature)
def inference_system(applicant_data: dict, preprocessor, calibrated_model, shap_explainer, best_threshold, top_n_features=5):
    """
    Predicts loan decision and probability of default for a new applicant,
    and provides local SHAP explanations.

    Args:
        applicant_data (dict): A dictionary of new applicant parameters.
        preprocessor: The fitted ColumnTransformer preprocessing pipeline.
        calibrated_model: The fitted CalibratedClassifierCV model.
        shap_explainer: The fitted SHAP TreeExplainer.
        best_threshold (float): The optimal decision threshold.
        top_n_features (int): Number of top SHAP features to display.

    Returns:
        dict: A dictionary containing prediction, probability of default, and SHAP explanations.
    """

    # 1. Create a DataFrame from applicant_data, ensuring correct column order
    input_df = pd.DataFrame([applicant_data], columns=X_train_columns) # Use loaded columns

    # 2. Apply the trained preprocessing pipeline
    processed_input = preprocessor.transform(input_df)

    # Convert processed_input sparse matrix to dense DataFrame for SHAP explanation
    # The feature names derived from the preprocessor are needed here
    ohe_feature_names = preprocessor.named_transformers_['cat'].named_steps['onehot'].get_feature_names_out(categorical_features)
    processed_feature_names_inference = numerical_features + ohe_feature_names.tolist()

    processed_input_df = pd.DataFrame(
        processed_input.toarray(),
        columns=processed_feature_names_inference
    )

    # 3. Use the calibrated champion model to predict PD and decision
    prob_default = calibrated_model.predict_proba(processed_input)[:, 1][0]
    decision = 'Reject' if prob_default >= best_threshold else 'Approve'

    # 4. Provide top reasons using local SHAP explanations
    shap_values_output = shap_explainer.shap_values(processed_input_df.iloc[[0]])

    if isinstance(shap_values_output, list):
        # For TreeExplainer, shap_values returns a list of arrays for multi-class, or a single array for binary
        if len(shap_values_output) == 2:
            shap_values_instance = shap_values_output[1][0] # Class 1 SHAP values, first instance
        else:
            shap_values_instance = shap_values_output[0]
    else: # If shap_values_output is directly the 2D array for the positive class
        shap_values_instance = shap_values_output[0]

    expected_value_for_plot = shap_explainer.expected_value


    # Create a DataFrame for SHAP values and sort by absolute magnitude
    shap_df = pd.DataFrame({
        'feature': processed_feature_names_inference,
        'shap_value': shap_values_instance
    }).sort_values(by='shap_value', ascending=False, key=abs)

    # Get top N features contributing to the prediction
    top_shap_features = shap_df.head(top_n_features)
    explanation = top_shap_features.to_dict(orient='records')

    # Generate a local SHAP force plot
    print(f"\nSHAP Force Plot for this {decision} decision:")
    shap.initjs()
    shap.force_plot(expected_value_for_plot, shap_values_instance, processed_input_df.iloc[0], matplotlib=True, show=False)
    plt.title(f'Local Explanation for {decision} (PD: {prob_default:.4f})')
    plt.show()

    return {
        'loan_decision': decision,
        'probability_of_default': prob_default,
        'top_shap_reasons': explanation
    }

# --- Example of user input ---
# This dictionary needs to contain all the original features that the model expects (X_train_columns)
# It's crucial that these values are realistic and match the data types of the original features.
# You would typically gather this data from a new loan applicant.

# Example: An applicant likely to be Approved
applicant_data_example_approved = {
    'loan_amnt': 10000.0,
    'term': ' 36 months',
    'int_rate': 7.5,
    'grade': 'A',
    'sub_grade': 'A4',
    'home_ownership': 'MORTGAGE',
    'annual_inc': 75000.0,
    'verification_status': 'Verified',
    'pymnt_plan': 'n',
    'purpose': 'debt_consolidation',
    'zip_code': '921xx',
    'addr_state': 'CA',
    'dti': 15.0,
    'delinq_2yrs': 0.0,
    'earliest_cr_line': 'Jan-2005',
    'inq_last_6mths': 0.0,
    'open_acc': 10.0,
    'revol_bal': 15000.0,
    'revol_util': 30.0,
    'total_acc': 25.0,
    'initial_list_status': 'f',
    'collections_12_mths_ex_med': 0.0,
    'acc_now_delinq': 0.0,
    'chargeoff_within_12_mths': 0.0,
    'delinq_amnt': 0.0,
    'pub_rec_bankruptcies': 0.0,
    'tax_liens': 0.0,
    'application_type': 'Individual',
    'disbursement_method': 'Cash'
}

# Example: An applicant likely to be Rejected (e.g., higher risk factors)
applicant_data_example_rejected = {
    'loan_amnt': 25000.0,
    'term': ' 60 months',
    'int_rate': 18.0,
    'grade': 'D',
    'sub_grade': 'D3',
    'home_ownership': 'RENT',
    'annual_inc': 40000.0,
    'verification_status': 'Not Verified',
    'pymnt_plan': 'n',
    'purpose': 'credit_card',
    'zip_code': '100xx',
    'addr_state': 'NY',
    'dti': 35.0,
    'delinq_2yrs': 1.0,
    'earliest_cr_line': 'Mar-2015',
    'inq_last_6mths': 2.0,
    'open_acc': 5.0,
    'revol_bal': 30000.0,
    'revol_util': 85.0,
    'total_acc': 12.0,
    'initial_list_status': 'w',
    'collections_12_mths_ex_med': 0.0,
    'acc_now_delinq': 0.0,
    'chargeoff_within_12_mths': 0.0,
    'delinq_amnt': 0.0,
    'pub_rec_bankruptcies': 0.0,
    'tax_liens': 0.0,
    'application_type': 'Individual',
    'disbursement_method': 'Cash'
}

print("\n--- Running Inference for Example Approved Applicant ---")
prediction_approved = inference_system(applicant_data_example_approved, preprocessor, calibrated_lgbm, explainer, best_threshold)
print(prediction_approved)

print("\n--- Running Inference for Example Rejected Applicant ---")
prediction_rejected = inference_system(applicant_data_example_rejected, preprocessor, calibrated_lgbm, explainer, best_threshold)
print(prediction_rejected)